### ISSUE TITLE
adb not found

### ISSUE THREAD

**Issue by paganaye** [ds300/android-capture#1]
```
C:\>npx android-capture video
npx: installed 91 in 5.462s
android-capture 1.2.1
ERROR  adb not found
```

Perhaps give us a way to tell where adb is:
```
npx android-capture video adb "C:\Users\pascal\AppData\Local\Android\Sdk\platform-tools\adb.exe"
```

**Comment by ds300** [comment]
Hi 👋🏼 Thanks for the report!

You can put `adb` in your terminal path by following the instructions here: https://lifehacker.com/the-easiest-way-to-install-androids-adb-and-fastboot-to-1586992378

I'm also open to adding an `--adb-path` option if people need it!

I don't code on Windows so I could use some guidance on what people might prefer :)

**Comment by ds300** [comment]
I just added support for the ANDROID_HOME and ANDROID_SDK_ROOT environment variables. Hopefully that will take care of most situations where people do indeed have the android dev tools installed. 

https://github.com/ds300/android-capture/commit/66193a94408364fa71441d8fab488a28977bc0e6

Feel free to open another issue if you still feel an `--adb-path` option would be useful 🙏🏼
